Feature/gatk4.2
UMCUGenetics/NextflowModules pull request #64
Opened 2022-03-24 09:36 UTC by melferink

* Includes Modules for GATK 4.2.1.0
* Including gzip option for output VCF files

2022-04-05 13:06 UTC, lvanoijen requested changes
Besides the small typo in SelectVariants.nf it is looking ok.
There is also an improvement you can make looking at the coding guidelines (wiki):
-Clear code: Avoid lines longer than 127 characters. -> split long lines in the output and script sections

2022-04-15 09:14 UTC, melferink commented on GATK/4.2.1.0/SelectVariants.nf
> +        -variant ${vcf_file} \
Nice catch :)

2022-04-22 11:06 UTC, lvanoijen approved these changes
Approved

2022-04-22 11:06 UTC, lvanoijen approved these changes

2022-04-22 11:35 UTC, sawibo approved these changes

2022-04-22 11:40 UTC, merged