Feature/use tmpdir gatk
UMCUGenetics/NextflowModules pull request #73
Opened 2023-07-07 10:44 UTC by ellendejong

2023-07-20 13:35 UTC, rernst requested changes
Some small inconsistencies. Did you check Picard behaviour? Since it is also developed by broad.

2023-07-20 13:35 UTC, rernst commented on GATK/3.8-1-0-gf15c1c3ef/CombineVariants.nf
> +        java -Xmx${task.memory.toGiga()-4}G -Djava.io.tmpdir=\$TMPDIR -jar ${params.gatk_path} -T CombineVariants --reference_sequence ${params.genome} -V ${input_files} --out ${analysis_id}.vcf ${pa
Also split on multiple lines?

2023-07-20 13:35 UTC, rernst commented on GATK/4.1.3.0/MergeVCFs.nf
> +        --TMP_DIR \$TMPDIR
Gaat dit goed in combinatie met met: `-Djava.io.tmpdir=\$PWD"`

2023-07-20 13:35 UTC, rernst commented on GATK/4.1.3.0/SplitNCigarReads.nf
> +        gatk --java-options "-Xmx${task.memory.toGiga()-4}g -Djava.io.tmpdir=\$TMPDIR" \
`--tmp-dir` vergeten?

2023-07-24 08:47 UTC, ellendejong commented on GATK/4.1.3.0/SplitNCigarReads.nf
> +        gatk --java-options "-Xmx${task.memory.toGiga()-4}g -Djava.io.tmpdir=\$TMPDIR" \
configured as `$PWD`, will change.

2023-07-24 08:56 UTC, ellendejong commented
> Some small inconsistencies. Did you check Picard behaviour? Since it is also developed by broad.

Added java tmpdir to PICARD.

2023-07-24 09:03 UTC, rernst approved these changes

2023-08-01 08:43 UTC, merged